In [5]:
# importando bibliotecas

import pandas as pd
from apyori import apriori
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [9]:
# definindo o df

df = pd.read_csv('compras.csv', header=None)

In [12]:
# eae df, ta funfando?

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,cliente,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
1,JÚLIO DEMARQUE,limão,peito de peru,manga,cerveja,picanha,carvão,sal,linguiça,mel,geleia,cereal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MAYCON SOARES,salsicha,cerveja,picanha,catchup,geleia,cebola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,WEMERSON NETO,queijo,frutas,chá,alface,granola,feijão,farinha de trigo,suco de laranja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,JOÃO DEMARQUE,pimenta,sardinha enlatada,barra de cereal,molho de tomate,gelatina,vinho branco,pão,tempero pronto,vinho tinto,presunto,arroz,feijão,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# pegando uniques
uniques = df[0].unique()
print(uniques)

['cliente' 'JÚLIO DEMARQUE' 'MAYCON SOARES' 'WEMERSON NETO'
 'JOÃO DEMARQUE' 'MAYCON SANTOS' 'PEDRO SOARES' 'OTÁVIO NETO'
 'VICTOR NETO' 'GABRIEL NETO' 'MAYCON OLIVEIRA' 'MAYCON SILVA'
 'MAYCON RODRIGUES' 'GABRIEL SANTOS' 'LUIZ OLIVEIRA' 'WEMERSON SANTOS'
 'PEDRO CARDOSO' 'JÚLIO RODRIGUES' 'SÁVIO SOARES' 'WEMERSON SOARES'
 'VICTOR RODRIGUES' 'FILIPE LIMA' 'MAYCON DEMARQUE' 'ALYSON SILVA'
 'OTÁVIO CARDOSO' 'JOÃO BANDEIRA' 'ALYSON SOARES' 'GABRIEL CARDOSO'
 'SERGIO CARDOSO' 'SÁVIO CARDOSO' 'JÚLIO SILVA' 'ALYSON LIMA'
 'GABRIEL NÁPOLES' 'SERGIO SILVA' 'JOÃO OLIVEIRA' 'GABRIEL BANDEIRA'
 'VICTOR COSTA' 'SÁVIO NETO' 'LUIZ SILVA' 'JÚLIO BANDEIRA' 'GUSTAVO CRUZ'
 'OTÁVIO MASSI' 'DANIEL CRUZ' 'LUIZ SOARES' 'DANIEL SILVA' 'DAVI SILVA'
 'SÁVIO CRUZ' 'WEMERSON RODRIGUES' 'SERGIO BANDEIRA' 'GABRIEL SOARES'
 'FILIPE CARDOSO' 'GABRIEL CRUZ' 'LUIZ CARDOSO' 'VANESSA SANTOS'
 'PEDRO COSTA' 'JÚLIO MASSI' 'GABRIEL SILVA' 'DANIEL OLIVEIRA'
 'DAVI NÁPOLES' 'WEMERSON CRUZ' 'GABRIEL RODRIGUES' 'VANESSA MASSI'
 'JÚLIO CRUZ' 'FILIPE SANTOS' 'WEMERSON BANDEIRA' 'PEDRO CRUZ'
 'DAVI DEMARQUE' 'OTÁVIO RODRIGUES' 'JÚLIO LIMA' 'LUIZ RODRIGUES'
 'SERGIO RODRIGUES' 'FILIPE CRUZ' 'SÁVIO SILVA' 'DAVI OLIVEIRA'
 'DAVI NETO' 'DANIEL NÁPOLES' 'WEMERSON LIMA' 'ALYSON CARDOSO'
 'MAYCON NÁPOLES' 'DAVI BANDEIRA' 'SERGIO SANTOS' 'VANESSA NETO'
 'FILIPE SOARES' 'PEDRO NETO' 'DANIEL SANTOS' 'OTÁVIO OLIVEIRA'
 'DAVI SOARES' 'JOÃO LIMA' 'DANIEL LIMA' 'SERGIO NETO' 'WEMERSON OLIVEIRA'
 'SERGIO COSTA' 'JÚLIO SANTOS' 'GUSTAVO CARDOSO' 'WEMERSON COSTA'
 'SERGIO DEMARQUE' 'SERGIO NÁPOLES' 'PEDRO SANTOS' 'ALYSON CRUZ'
 'GUSTAVO NETO' 'JÚLIO NÁPOLES' 'OTÁVIO BANDEIRA' 'PEDRO OLIVEIRA'
 'SÁVIO OLIVEIRA' 'LUIZ BANDEIRA' 'GUSTAVO RODRIGUES' 'WEMERSON SILVA'
 'PEDRO NÁPOLES' 'ALYSON SANTOS' 'GUSTAVO LIMA' 'SERGIO LIMA'
 'OTÁVIO SANTOS' 'WEMERSON NÁPOLES' 'WEMERSON CARDOSO' 'ALYSON RODRIGUES'
 'SERGIO MASSI' 'GUSTAVO COSTA' 'DANIEL RODRIGUES' 'GABRIEL DEMARQUE'
 'PEDRO DEMARQUE' 'VANESSA COSTA' 'LUIZ SANTOS' 'GUSTAVO DEMARQUE'
 'FILIPE NÁPOLES' 'SERGIO CRUZ' 'SERGIO SOARES' 'DAVI RODRIGUES'
 'LUIZ LIMA' 'DAVI CRUZ' 'FILIPE BANDEIRA' 'OTÁVIO CRUZ' 'GUSTAVO SANTOS'
 'OTÁVIO DEMARQUE' 'DANIEL NETO' 'ALYSON DEMARQUE' 'SERGIO OLIVEIRA'
 'VANESSA LIMA' 'DANIEL BANDEIRA' 'OTÁVIO SILVA' 'VICTOR LIMA'
 'FILIPE DEMARQUE' 'JÚLIO NETO' 'JÚLIO CARDOSO' 'LUIZ NETO' 'ALYSON MASSI'
 'GUSTAVO MASSI' 'SÁVIO BANDEIRA' 'GABRIEL LIMA' 'JOÃO COSTA'
 'SÁVIO MASSI' 'MAYCON BANDEIRA' 'SÁVIO DEMARQUE' 'JOÃO NETO' 'DAVI COSTA'
 'FILIPE MASSI' 'VICTOR SILVA' 'VICTOR BANDEIRA' 'VANESSA BANDEIRA'
 'VICTOR OLIVEIRA' 'JÚLIO SOARES' 'JOÃO RODRIGUES' 'DANIEL DEMARQUE'
 'GUSTAVO SOARES' 'SÁVIO NÁPOLES' 'MAYCON NETO' 'VANESSA DEMARQUE'
 'MAYCON CARDOSO' 'LUIZ NÁPOLES' 'PEDRO SILVA' 'PEDRO LIMA'
 'VICTOR SOARES' 'OTÁVIO SOARES' 'ALYSON NETO' 'FILIPE COSTA'
 'SÁVIO COSTA' 'SÁVIO SANTOS' 'MAYCON LIMA' 'LUIZ DEMARQUE'
 'FILIPE RODRIGUES' 'ALYSON COSTA' 'GUSTAVO OLIVEIRA' 'MAYCON COSTA'
 'WEMERSON DEMARQUE' 'ALYSON NÁPOLES' 'GUSTAVO SILVA' 'DANIEL CARDOSO'
 'PEDRO BANDEIRA' 'GUSTAVO NÁPOLES' 'DANIEL SOARES' 'JOÃO CARDOSO'
 'VICTOR MASSI' 'ALYSON BANDEIRA' 'WEMERSON MASSI' 'DAVI LIMA'
 'PEDRO MASSI' 'VICTOR DEMARQUE' 'OTÁVIO NÁPOLES' 'FILIPE NETO'
 'JÚLIO COSTA' 'FILIPE SILVA' 'DAVI MASSI' 'LUIZ CRUZ' 'LUIZ COSTA'
 'VANESSA RODRIGUES' 'OTÁVIO LIMA' 'JOÃO SILVA' 'GABRIEL MASSI'
 'SÁVIO LIMA' 'DAVI CARDOSO' 'JOÃO SANTOS' 'MAYCON CRUZ'
 'GUSTAVO BANDEIRA' 'GABRIEL COSTA' 'VANESSA CRUZ' 'DANIEL COSTA'
 'VICTOR SANTOS' 'JOÃO NÁPOLES' 'MAYCON MASSI' 'JOÃO MASSI'
 'VICTOR CARDOSO' 'ALYSON OLIVEIRA' 'VANESSA SOARES' 'FILIPE OLIVEIRA'
 'PEDRO RODRIGUES' 'VANESSA SILVA' 'OTÁVIO COSTA' 'SÁVIO RODRIGUES'
 'JOÃO CRUZ' 'GABRIEL OLIVEIRA' 'DANIEL MASSI' 'VANESSA OLIVEIRA'
 'VANESSA CARDOSO' 'JOÃO SOARES' 'VICTOR CRUZ' 'VANESSA NÁPOLES'
 'LUIZ MASSI']

In [16]:
# adaptando CSV para aplicação do FP Growth
df_compras_lista = df.apply(lambda x: x.dropna().tolist(), axis=1).tolist()

te = TransactionEncoder()
te_ary = te.fit(df_compras_lista).transform(df_compras_lista)

# Converte o array resultante em um DataFrame pandas
df_onehot = pd.DataFrame(te_ary, columns=te.columns_)

# Agora você pode aplicar o fpgrowth no DataFrame one-hot
frequent_itemsets = fpgrowth(df_onehot, min_support=0.003,use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=3)

In [17]:
rules.size

14540

In [18]:
# imprimindo as regras mais importantes ordenadas por lift
rules = rules.sort_values(by='lift', ascending=False)

In [19]:
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
683,"(hambúrguer, catchup)","(mostarda, batata frita, cerveja)",0.014499,0.005599,0.0041,0.282759,50.497660,0.004018,1.386424,0.994618
678,"(mostarda, batata frita, cerveja)","(hambúrguer, catchup)",0.005599,0.014499,0.0041,0.732143,50.497660,0.004018,3.679205,0.985717
682,"(hambúrguer, mostarda)","(catchup, batata frita, cerveja)",0.010999,0.007399,0.0041,0.372727,50.373587,0.004018,1.582407,0.991049
679,"(catchup, batata frita, cerveja)","(hambúrguer, mostarda)",0.007399,0.010999,0.0041,0.554054,50.373587,0.004018,2.217760,0.987455
1037,"(azeite, salada)","(cenoura, vinagre, tomate)",0.015098,0.005399,0.0040,0.264901,49.060584,0.003918,1.353015,0.994635
1024,"(cenoura, vinagre, tomate)","(azeite, salada)",0.005399,0.015098,0.0040,0.740741,49.060584,0.003918,3.798906,0.984935
1233,"(salada, alface, vinagre)","(azeite, tomate)",0.007799,0.011099,0.0042,0.538462,48.514900,0.004113,2.142619,0.987086
1252,"(azeite, tomate)","(salada, alface, vinagre)",0.011099,0.007799,0.0042,0.378378,48.514900,0.004113,1.596149,0.990380
1039,"(azeite, tomate)","(cenoura, salada, vinagre)",0.011099,0.007599,0.0040,0.360360,47.420578,0.003915,1.551500,0.989899
1022,"(cenoura, salada, vinagre)","(azeite, tomate)",0.007599,0.011099,0.0040,0.526316,47.420578,0.003915,2.087680,0.986408

In [20]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
683,"(hambúrguer, catchup)","(mostarda, batata frita, cerveja)",0.014499,0.005599,0.004100,0.282759,50.497660,0.004018,1.386424,0.994618
678,"(mostarda, batata frita, cerveja)","(hambúrguer, catchup)",0.005599,0.014499,0.004100,0.732143,50.497660,0.004018,3.679205,0.985717
682,"(hambúrguer, mostarda)","(catchup, batata frita, cerveja)",0.010999,0.007399,0.004100,0.372727,50.373587,0.004018,1.582407,0.991049
679,"(catchup, batata frita, cerveja)","(hambúrguer, mostarda)",0.007399,0.010999,0.004100,0.554054,50.373587,0.004018,2.217760,0.987455
1037,"(azeite, salada)","(cenoura, vinagre, tomate)",0.015098,0.005399,0.004000,0.264901,49.060584,0.003918,1.353015,0.994635
...,...,...,...,...,...,...,...,...,...,...
835,(leite),(açúcar),0.070693,0.062394,0.013799,0.195191,3.128373,0.009388,1.165005,0.732099
561,(cerveja),(batata frita),0.075392,0.059994,0.014099,0.187003,3.117023,0.009575,1.156223,0.734561
560,(batata frita),(cerveja),0.059994,0.075392,0.014099,0.235000,3.117023,0.009575,1.208637,0.722528
64,"(presunto, queijo)",(geleia),0.057594,0.048295,0.008499,0.147569,3.055574,0.005718,1.116460,0.713842
65,(geleia),"(presunto, queijo)",0.048295,0.057594,0.008499,0.175983,3.055574,0.005718,1.143673,0.706867